Improve the FILSYS configuration model and options
- expect valid FILSYS records from the FSMAPFILE and FSCOMMAND
- document the syntax of valid FILSYS records (from the autofs src)
- use 2 sed variables for the two modifications

And plenty of additional tuning.

Getting closer, but this is going to be a bitch to implement.

diff --git a/lib_check_cfg_file b/lib_check_cfg_file
--- a/lib_check_cfg_file
+++ b/lib_check_cfg_file
@@ -90,7 +90,7 @@ function check_cfg_file {
 
     # Check the UID and GID values
     if (( UIDMIN > UIDMAX || GIDMIN > GIDMAX )) ; then
-        echo "ERROR: UIDMAX / GIDMAX cannot be inferior to than UIDMIN / GIDMIN." >&2
+        echo "ERROR: UIDMAX / GIDMAX cannot be inferior to UIDMIN / GIDMIN." >&2
         exit 1
     fi
 
@@ -105,15 +105,22 @@ function check_cfg_file {
     fi
 
 
-    # HOMEDIRSED and FSSERVER can't really be checked -- they can be anything.
+    # Some of the FILSYS variables can't be checked, so nothing to do there:
+    # HOMESEDEXPORT, HOMESEDMOUNT, NFSSERVER
 
     # I don't really want to check the FSTYPE. The documentation on the Linux
-    # side is poor at best. I can't find an authoritative list of what is or is
-    # not supported, so every case imaginable will need to be tested.
+    # side isn't very good. I can't find an authoritative list of what is or is
+    # not supported by autofs, and anyway every case imaginable would need to be
+    # tested and validated.
     # So yeah, let it be whatever the user wants and caveat emptor.
 
     if [[ "$FSMAPFILE" && ! -r "$FSMAPFILE" ]] ; then
-        echo "ERROR: The automount map file doesn't exist or is not readable: $FSMAPFILE" >&2
+        echo "ERROR: The FSMAPFILE doesn't exist or is not readable: $FSMAPFILE" >&2
+        exit 1
+    fi
+
+    if [[ "$FSCOMMAND" && ! type "$FSMAPFILE" &> /dev/null ]] ; then
+        echo "ERROR: The FSCOMMAND doesn't exist, is not executable or is not in the PATH: $FSCOMMAND" >&2
         exit 1
     fi
 
